In [1]:
# Fuel efficiency using multiple linear regreession

import pandas as pd

In [3]:
dataSet = pd.read_csv("fuel_efficiency.csv")

In [4]:
dataSet

,Trip_ID,Avg_Speed,Distance,Sudden_Accelerations,Hard_Brakes,Road_Type,Engine_Load,Tire_Pressure,Outside_Temp,Fuel_Efficiency
0,1,45,15,2,1,Highway,65,32,75,28.5
1,2,25,5,8,6,City,85,28,68,18.2
2,3,60,30,1,0,Highway,55,34,82,34.0
3,4,35,10,5,4,Rural,75,30,72,22.1
4,5,50,20,3,2,Highway,70,33,78,27.8
5,6,20,3,10,8,City,90,27,65,15.4
6,7,55,25,0,1,Highway,60,35,80,32.5
7,8,40,12,4,3,Rural,80,29,70,24.3
8,9,30,8,7,5,City,88,28,67,17.9
9,10,65,35,1,0,Highway,50,36,85,36.7

In [5]:
dataSet = pd.get_dummies(dataSet, drop_first=True) # to handle the nominal data (state coloum)

In [6]:
dataSet # verifying

,Trip_ID,Avg_Speed,Distance,Sudden_Accelerations,Hard_Brakes,Engine_Load,Tire_Pressure,Outside_Temp,Fuel_Efficiency,Road_Type_Highway,Road_Type_Rural
0,1,45,15,2,1,65,32,75,28.5,True,False
1,2,25,5,8,6,85,28,68,18.2,False,False
2,3,60,30,1,0,55,34,82,34.0,True,False
3,4,35,10,5,4,75,30,72,22.1,False,True
4,5,50,20,3,2,70,33,78,27.8,True,False
5,6,20,3,10,8,90,27,65,15.4,False,False
6,7,55,25,0,1,60,35,80,32.5,True,False
7,8,40,12,4,3,80,29,70,24.3,False,True
8,9,30,8,7,5,88,28,67,17.9,False,False
9,10,65,35,1,0,50,36,85,36.7,True,False

In [7]:
dataSet.columns

Index(['Trip_ID', 'Avg_Speed', 'Distance', 'Sudden_Accelerations',
       'Hard_Brakes', 'Engine_Load', 'Tire_Pressure', 'Outside_Temp',
       'Fuel_Efficiency', 'Road_Type_Highway', 'Road_Type_Rural'],
      dtype='object')

In [12]:
independent = dataSet[['Trip_ID', 'Avg_Speed', 'Distance', 'Sudden_Accelerations', 'Hard_Brakes', 'Engine_Load', 'Tire_Pressure', 'Outside_Temp', 'Road_Type_Highway', 'Road_Type_Rural']]

In [13]:
dependent = dataSet[['Fuel_Efficiency']]

In [14]:
independent

,Trip_ID,Avg_Speed,Distance,Sudden_Accelerations,Hard_Brakes,Engine_Load,Tire_Pressure,Outside_Temp,Road_Type_Highway,Road_Type_Rural
0,1,45,15,2,1,65,32,75,True,False
1,2,25,5,8,6,85,28,68,False,False
2,3,60,30,1,0,55,34,82,True,False
3,4,35,10,5,4,75,30,72,False,True
4,5,50,20,3,2,70,33,78,True,False
5,6,20,3,10,8,90,27,65,False,False
6,7,55,25,0,1,60,35,80,True,False
7,8,40,12,4,3,80,29,70,False,True
8,9,30,8,7,5,88,28,67,False,False
9,10,65,35,1,0,50,36,85,True,False

In [15]:
dependent

   Fuel_Efficiency
0             28.5
1             18.2
2             34.0
3             22.1
4             27.8
5             15.4
6             32.5
7             24.3
8             17.9
9             36.7

In [16]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(independent, dependent, test_size=0.30,random_state=0)

In [17]:
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(X_train,Y_train)

LinearRegression()

In [18]:
weight=regressor.coef_
weight

array([[-0.18844776,  0.35911433,  0.24876672, -0.13923716, -0.11852576,
        -0.03773282,  0.12741084, -0.35949898,  0.26573966, -0.4069984 ]])

In [19]:
bais=regressor.intercept_
bais

array([34.26597293])

In [20]:
y_pred=regressor.predict(X_test)

In [21]:
y_pred

array([[35.61474022],
       [19.92680094],
       [29.38810106]])

In [22]:
from sklearn.metrics import r2_score
r_score=r2_score(Y_test,y_pred)

In [23]:
r_score

0.9299597658872261

In [24]:
import pickle
filename="finalized_model_linear.sav"

In [25]:
pickle.dump(regressor,open(filename,'wb'))

In [27]:
independent

,Trip_ID,Avg_Speed,Distance,Sudden_Accelerations,Hard_Brakes,Engine_Load,Tire_Pressure,Outside_Temp,Road_Type_Highway,Road_Type_Rural
0,1,45,15,2,1,65,32,75,True,False
1,2,25,5,8,6,85,28,68,False,False
2,3,60,30,1,0,55,34,82,True,False
3,4,35,10,5,4,75,30,72,False,True
4,5,50,20,3,2,70,33,78,True,False
5,6,20,3,10,8,90,27,65,False,False
6,7,55,25,0,1,60,35,80,True,False
7,8,40,12,4,3,80,29,70,False,True
8,9,30,8,7,5,88,28,67,False,False
9,10,65,35,1,0,50,36,85,True,False

In [28]:
loaded_model=pickle.load(open("finalized_model_linear.sav",'rb'))
result=loaded_model.predict([[10,65,35,1,0,50,36,85,1,0]])
result

C:\Users\ahazz\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([[36.7]])